### ISSUE TITLE
Support Roary output

### ISSUE THREAD

**Issue by tseemann** [drpowell/FriPan#11]
https://github.com/sanger-pathogens/Roary

**Comment by alexjironkin** [comment]
I was wondering if we can work together to come up with a common data structure so we can plug in our core-accessory output?

**Comment by alexjironkin** [comment]
I just looked over the example data structure. I think we should be able to produce something very similar. I noticed that the gene names are locus IDs (?). Can we link them to NCBI locus from the info pop-up box? 

I can try adding relevant bits and create pull request?

**Comment by alexjironkin** [comment]
Does @andrewpage have any specific data in ROARY to display?

**Comment by andrewpage** [comment]
@alexjironkin no

**Comment by tseemann** [comment]
LOL I think you mean @andrewjpage not @andrewpage - sorry non-J Andrew ;)

**Comment by andrewpage** [comment]
No problem :smile:

**Comment by tseemann** [comment]
There is a `roary2fripan.py` in https://github.com/kwongj/roary2fripan

**Comment by drpowell** [comment]
Roary parsing added in 62483aeaf0f26ade0422b737d582490be180fa79
