### ISSUE TITLE
Is sort order alphabetical? 

### ISSUE THREAD

**Issue by tseemann** [drpowell/FriPan#13]
If we have a column in the .strains file that is an integer that we want to order by, does it work?

Or so we have to ensure zero-padding?   eg. 00 01 02 ... 73

**Comment by drpowell** [comment]
Set sort to numeric - not sure it will work in general, but in some rough tests it seemed an improvement
d5ef46bbf7222e4a64046dd946e6c6a1ab8acd64

**Comment by tseemann** [comment]
OK thanks.
