### ISSUE TITLE
Need to delete old VBC FriPan repo, and update the repo link in the README file

### ISSUE THREAD

**Issue by andersgs** [drpowell/FriPan#15]
Hi David.

At the moment, this repo does not come up on a Google search (at least not on the first page), and the repo link in the README file is out of date too.

Cheers.

Anders.

**Comment by drpowell** [comment]
thanks, will do

**Comment by andersgs** [comment]
This line still needs to change in the installation section... Sorry, I should've been more specific:

git clone https://github.com/Victorian-Bioinformatics-Consortium/FriPan

**Comment by drpowell** [comment]
Ahh, right, fixed, thx.
