### ISSUE TITLE
MDS scatterplot

### ISSUE THREAD

**Issue by kwongj** [drpowell/FriPan#2]
In my browser, the MDS scatterplot is positioned over part of the Fripan image at present. Are other people also experiencing this? I've tried this with google chrome and with safari.

**Comment by drpowell** [comment]
Is this still a problem?

**Comment by tseemann** [comment]
I haven't noticed it.

**Comment by drpowell** [comment]
Calling this closed.  I think it could happen if there is a long name given in one of the option fields
