### ISSUE TITLE
Not connecting to FriPan 

### ISSUE THREAD

**Issue by Anuravi123** [drpowell/FriPan#34]
Hello, 

I am not sure if I am doing the right thing, I tried to run FriPan but I get this error 

ubuntu@anuradhr:~/FriPan$ ./server.sh 
Run: make compile
      (or 'make debug' for development)
http://localhost:8030/pan.html
Serving HTTP on 0.0.0.0 port 8030 ...
127.0.0.1 - - [17/Apr/2018 08:43:26] "GET /pan.html HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 08:43:26] "GET /pan.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 08:43:26] "GET /build.js HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 08:43:26] "GET /pan.index HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 08:43:26] code 404, message File not found
127.0.0.1 - - [17/Apr/2018 08:43:26] "GET /pan.proteinortho HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2018 08:43:26] code 404, message File not found
127.0.0.1 - - [17/Apr/2018 08:43:26] "GET /pan.roary HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2018 08:43:27] "GET /pan.html HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 08:43:27] "GET /pan.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 08:43:27] "GET /build.js HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 08:43:28] "GET /pan.index HTTP/1.1" 200 -
127.0.0.1 - - [17/Apr/2018 08:43:28] code 404, message File not found
127.0.0.1 - - [17/Apr/2018 08:43:28] "GET /pan.proteinortho HTTP/1.1" 404 -
127.0.0.1 - - [17/Apr/2018 08:43:28] code 404, message File not found
127.0.0.1 - - [17/Apr/2018 08:43:28] "GET /pan.roary HTTP/1.1" 404 -

Can you please help mw with this. I am tring to run a roary output and I have converted them into FriPan input files.

Many thanks for your help!

Anu

**Comment by tseemann** [comment]
How did you create the `pan.proteinortho` from Roary's output?

**Comment by Anuravi123** [comment]
Hello Seeman!

Thank you for your reply and apologies for my late reply. I created the pan.proteinortho using Jason Kwong converter script. I am having problems in making the interactive web display. I am running Fripan in a MacOS. I installed npm, downloaded Fripan and did "install npm". 

Here after installing node, I got:
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.2/fse-v1.2.2-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.2 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/ravia/FriPan/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
npm notice created a lockfile as package-lock.json. You should commit this file.
added 252 packages in 23.636s

I then tried "make compile" which completed with no errors. Then, I tried to do "./server.sh" and I get

N113038:FriPan ravia$ ./server.sh 
Run: make compile
      (or 'make debug' for development)
http://localhost:8030/pan.html
Serving HTTP on 0.0.0.0 port 8030 ...

With no more response. I am not sure how I get the interactive web display. I feel like this could be a question challenging my computer skills. I would really like some help.

Thank you!

Anu

**Comment by Anuravi123** [comment]
Ok, I solved it!! I add the datafiles to the public_html/fripan. I then editted the index.html. I then editted my html link to include the name of my files! 

It worked but is there a way to get a SVG format of the figures?

Anu
