### ISSUE TITLE
server.sh not working

### ISSUE THREAD

**Issue by EllistonV** [drpowell/FriPan#48]
after running the command `./server.sh` I got the following message:

`Run: make compile
      (or 'make debug' for development)
http://localhost:8030/pan.html
/home/elliston/miniconda3/bin/python: No module named SimpleHTTPServer`

Then, after running the command `firefox http://localhost:8030/pan.html`, firefox opens with an error page (the one that says unable to connect).

I also cannot visualize the roary data.

**Comment by gpmoran** [comment]
I have the same error. It seems SimpleHTTPServe no longer works.....

**Comment by drpowell** [comment]
Thx for the report.  I was using python2 only.  It should now work with python2 or python3

**Comment by gpmoran** [comment]
Thanks for looking into it. The browser now opens in Firefox, but it seems to have problems locating the files in the FriPan folder:

(base) Garys-MacBook-Pro:FriPan garymoran$ ./server.sh
Run: make compile
      (or 'make debug' for development)
http://localhost:8030/pan.html
Serving HTTP on :: port 8030 (http://[::]:8030/) ...
::ffff:127.0.0.1 - - [13/May/2021 08:27:54] "GET /pan.html HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [13/May/2021 08:27:54] "GET /build.js HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [13/May/2021 08:27:54] code 404, message File not found
::ffff:127.0.0.1 - - [13/May/2021 08:27:54] "GET /pan.proteinortho HTTP/1.1" 404 -
::ffff:127.0.0.1 - - [13/May/2021 08:27:54] "GET /pan.index HTTP/1.1" 200 -
::ffff:127.0.0.1 - - [13/May/2021 08:27:54] code 404, message File not found
::ffff:127.0.0.1 - - [13/May/2021 08:27:54] "GET /pan.roary HTTP/1.1" 404 -
